name: Send SMS
on:
    push:
        branches:
            - master
env:
    NPM_TOKEN: ed2e421d2a0498630ba9cba7695bde8ff3187bde

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: 'registry setup'
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
                  scope: '@deepanshu195'
            - name: install
              run: npm ci
            - name: build
              run: npm run build
            # - name: semantic-release
            # run: npx semantic-release --debug
            - name: Set npm registry
              run: npm config set @deepanshu195:registry https://npm.pkg.github.com
            - name: publish
              run: npm publish
              # env:
              #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              # NPM_TOKEN: 1b23278c0101138c490ccd74c24fc9155e40045f
