name: Send SMS
on:
    push:
        branches:
            - master
env:
    NPM_TOKEN: ce46fc67d3db91a4585c3f17be48298d377c1290

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: 'registry setup'
              uses: actions/setup-node@v1
              with:
                  registry-url: 'https://npm.pkg.github.com'
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: install
              run: npm ci
            - name: build
              run: npm run build
            - name: semantic-release
              run: npx semantic-release --debug
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ce46fc67d3db91a4585c3f17be48298d377c1290
